const fs = require('fs');

// Read existing otherWaysThrough.ts
let owt = fs.readFileSync('src/data/otherWaysThrough.ts', 'utf8');

const newResources = [
  {
    id: 'greyhound-home-free',
    name: 'Greyhound Home Free Program',
    organization: 'National Runaway Safeline & Greyhound Lines, Inc.',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'TRANSPORTATION_EMERGENCY_TRAVEL',
    barrierCategories: ['transportation-gas', 'money-now'],
    matchTags: ['TRANSPORTATION', 'BUS_TICKET', 'YOUTH', 'EMERGENCY_TRAVEL', 'ESCAPE', 'NO_POLICE_REPORT', 'NO_SHELTER_STAY'],
    whatItCanHelpWith: 'Provides free one-way Greyhound bus tickets to youth (ages 12–21) fleeing abusive, dangerous, or unstable home situations to travel to a verified safe parent, legal guardian, or licensed transitional facility.',
    whatItActuallyProvides: 'Direct-issued one-way commercial bus ticket with meal stipend allowance at major transfer hubs.',
    assistanceShapes: ['BUS_TICKET', 'OTHER'],
    paymentMethod: 'SERVICE_DIRECT',
    typicalAmount: '100% free one-way long-distance bus ticket',
    knownFundingLimits: 'Limit of 2 Home Free tickets per individual lifetime; ticket must be issued to a verified safe destination',
    eligibility: 'Must be between the ages of 12 and 21. Must have an open incident report on file with the National Runaway Safeline (can be opened during call) and be traveling to a verified safe guardian or licensed shelter facility.',
    documentationRequired: [
      'Telephone intake interview with National Runaway Safeline advocate',
      'Name and phone number of receiving parent, guardian, or licensed transitional home coordinator',
      'Government ID, student ID, or advocate identity confirmation for station will-call pick up'
    ],
    referralRequirement: 'Must be processed through National Runaway Safeline advocate conference',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'None',
    employmentDependency: 'None',
    applicationWindow: 'Immediate (intake completed in 2–4 hours)',
    whatCanBlockAccess: [
      'Strict age window: applicant must be 12 to 21 years old',
      'Destination must be verbally confirmed as safe by NRS advocate prior to ticket release',
      'Requires physical access to an operating Greyhound station or connecting partner depot'
    ],
    accessFrictions: ['NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED', 'CALL_ONLY', 'SAME_DAY_POSSIBLE'],
    whatToDoNext: 'Call 1-800-RUNAWAY (1-800-786-2929) or text 66008. Tell the advocate you need the Home Free transportation program.',
    howToApply: 'Call 1-800-RUNAWAY (1-800-786-2929) for 24/7 phone intake.',
    sourceUrl: 'https://www.1800runaway.org/youth-teens/home-free-transportation',
    primaryAuthoritativeSource: 'National Runaway Safeline & Greyhound Lines Inc. Program Charter',
    lastReviewedDate: '2026-08-28',
    dateLastVerified: '2026-08-28',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: 'Categorized in social service databases exclusively under runaway youth helplines rather than family violence escape or emergency transportation.',
    workaround: 'If an eligible youth (ages 12–21) is fleeing an unsafe family home or abusive guardian, the National Runaway Safeline advocate can conduct immediate phone intake and authorize a ticket without requiring law enforcement arrest.',
    accessNotes: 'Call 1-800-RUNAWAY (1-800-786-2929). Advocate coordinates directly with nearest Greyhound station. Ticket can be retrieved at will-call within hours.'
  },
  {
    id: 'salvation-army-service-extension-tx',
    name: 'Salvation Army Texas Service Extension (Rural Travel & Micro-Aid)',
    organization: 'The Salvation Army Texas Division',
    state: 'TX',
    geography: 'Texas Statewide (Rural / Non-Metro Counties)',
    scope: 'TEXAS_STATEWIDE',
    category: 'HYPERLOCAL_MICRO_AID',
    barrierCategories: ['transportation-gas', 'money-now', 'rent-deposit'],
    matchTags: ['TEXAS', 'RURAL', 'GAS_CARD', 'BUS_TICKET', 'HOTEL_VOUCHER', 'EMERGENCY_TRAVEL', 'NO_POLICE_REPORT'],
    whatItCanHelpWith: 'Provides emergency travel assistance (fuel vouchers, bus passes, and 1–2 night roadside emergency motel vouchers) and micro-aid in rural Texas counties without permanent Salvation Army corps buildings.',
    whatItActuallyProvides: 'Prepaid gas cards, Greyhound/bus vouchers, direct motel invoice payments, and emergency grocery cards.',
    assistanceShapes: ['GAS_CARD', 'BUS_TICKET', 'HOTEL_VOUCHER', 'GROCERY_CARD'],
    paymentMethod: 'SURVIVOR_DIRECT',
    typicalAmount: '$50 to $300 in emergency vouchers or travel assistance',
    knownFundingLimits: 'Discretionary funds allocated per rural volunteer committee; subject to monthly pool availability',
    eligibility: 'Resident or transient individual in a participating rural Texas county experiencing an emergency transportation breakdown or crisis displacement.',
    documentationRequired: [
      'Basic photo ID or proof of regional presence (flexible in emergency escape situations)',
      'Brief explanation of immediate travel destination or barrier shortfall'
    ],
    referralRequirement: 'Local volunteer committee contact or county sheriff / ministerial referral',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'Demonstrated emergency need',
    employmentDependency: 'None',
    applicationWindow: 'Same-day to 48 hours depending on local committee volunteer availability',
    whatCanBlockAccess: [
      'Only operates in rural and suburban counties that lack a permanent Salvation Army center',
      'Managed by local volunteer committees with variable response times'
    ],
    accessFrictions: ['NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED', 'SAME_DAY_POSSIBLE'],
    whatToDoNext: 'Contact the local county sheriff dispatcher, municipal library desk, or regional Divisional Service Extension director to reach the active local volunteer committee chair.',
    howToApply: 'Contact local volunteer committee liaison or regional Divisional Service Extension director.',
    sourceUrl: 'https://salvationarmytexas.org/service-extension/',
    primaryAuthoritativeSource: 'Salvation Army Texas Divisional Headquarters Guidelines',
    lastReviewedDate: '2026-08-25',
    dateLastVerified: '2026-08-25',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: '211 directories only index permanent Salvation Army brick-and-mortar shelter corps, missing the hundreds of volunteer Service Units in rural Texas counties.',
    workaround: 'Volunteer Service Units hold flexible emergency funds administered by local town committees (sheriffs, pastors, or librarians) who can issue instant gas vouchers, bus tickets, or 1–2 night motel stays.',
    accessNotes: 'Ask local county sheriff dispatch, county food pantry, or call the Divisional Service Extension office for the active local volunteer committee chair.'
  },
  {
    id: 'usbg-bartender-emergency-assistance',
    name: 'USBG Bartender Emergency Assistance Program (BEAP)',
    organization: 'USBG National Charity Foundation',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'INDUSTRY_EMERGENCY_FUNDS',
    barrierCategories: ['industry-hardship', 'money-now', 'rent-deposit', 'medical-dental'],
    matchTags: ['BARTENDER', 'BARBACK', 'FOOD_BEVERAGE', 'HOSPITALITY', 'CASH', 'RENT', 'NO_POLICE_REPORT', 'NO_SHELTER_STAY'],
    whatItCanHelpWith: 'Provides emergency financial grants to bartenders, barbacks, and bar servers experiencing catastrophic life events, emergency displacement, medical emergencies, or natural disasters.',
    whatItActuallyProvides: 'Direct cash assistance or vendor-direct payments for essential living expenses, rent, utilities, and emergency relocation.',
    assistanceShapes: ['DIRECT_CASH', 'VENDOR_PAYMENT', 'RENT', 'UTILITY_PAYMENT'],
    paymentMethod: 'SURVIVOR_DIRECT',
    typicalAmount: '$500 to $2,500 based on documented catastrophic shortfall',
    knownFundingLimits: 'Assessed on case-by-case basis; grants disbursed until monthly funding allotment is reached',
    eligibility: 'Must be a bartender, barback, or bar server with verifiable employment in the beverage hospitality industry. Does NOT require membership in the United States Bartenders\' Guild.',
    documentationRequired: [
      'Proof of employment in beverage hospitality (paystubs, W-2, 1099, or liquor license/schedule verification)',
      'Documentation verifying the catastrophic emergency or displacement shortfall',
      'Lease, utility, or medical bills supporting the requested amount'
    ],
    referralRequirement: 'None (self-apply online)',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'Demonstrated emergency financial crisis',
    employmentDependency: 'Beverage hospitality industry employment (bartender, barback, bar server)',
    applicationWindow: 'Within 90 days of catastrophic incident',
    whatCanBlockAccess: [
      'Requires verifiable bar industry employment documentation',
      'Crisis event must be unforeseen and catastrophic',
      'Processing time averages 2–4 weeks'
    ],
    accessFrictions: ['APPLICATION_REQUIRED', 'EMPLOYMENT_PROOF', 'NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED'],
    whatToDoNext: 'Visit usbgfoundation.org/beap and complete the online application. Upload paystubs and bill documentation.',
    howToApply: 'Apply online at usbgfoundation.org/beap.',
    sourceUrl: 'https://www.usbgfoundation.org/beap',
    primaryAuthoritativeSource: 'USBG National Charity Foundation BEAP Operating Guidelines',
    lastReviewedDate: '2026-08-22',
    dateLastVerified: '2026-08-22',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: 'Located exclusively within beverage industry professional networks; non-hospitality caseworkers never think to ask about bartending or bar service history.',
    workaround: 'Open to any bartender, barback, or bar server with verifiable industry employment. Does NOT require membership in the United States Bartenders\' Guild.',
    accessNotes: 'Apply online at usbgfoundation.org/beap with paystubs, liquor server permit, or employer work schedules.'
  },
  {
    id: 'entertainment-community-fund',
    name: 'Entertainment Community Fund Emergency Financial Assistance',
    organization: 'Entertainment Community Fund (Formerly The Actors Fund)',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'INDUSTRY_EMERGENCY_FUNDS',
    barrierCategories: ['industry-hardship', 'rent-deposit', 'utility-deposit', 'medical-dental', 'money-now'],
    matchTags: ['PERFORMING_ARTS', 'FILM', 'THEATRE', 'CREW', 'STAGEHAND', 'MUSICIAN', 'RENT', 'UTILITY', 'NO_POLICE_REPORT', 'NO_SHELTER_STAY'],
    whatItCanHelpWith: 'Provides emergency financial grants for essential living expenses (housing rent, mortgage, utilities, medical care, and relocation) to professionals in the performing arts and entertainment industries.',
    whatItActuallyProvides: 'Direct grant payments made to landlords, utility companies, or directly to applicant for documented emergency shortfalls.',
    assistanceShapes: ['DIRECT_CASH', 'VENDOR_PAYMENT', 'RENT', 'UTILITY_PAYMENT', 'MEDICAL'],
    paymentMethod: 'DIRECT_TO_VENDOR',
    typicalAmount: '$1,000 to $3,000 based on documented need and earnings history',
    knownFundingLimits: 'Limits based on industry tenure and documented crisis bills; direct creditor payment preferred',
    eligibility: 'Must demonstrate documented employment earnings in the performing arts or entertainment industry (performers, actors, crew, technicians, stagehands, hair/makeup, dancers, film/TV workers, musicians) with 3–5 years of industry earnings history.',
    documentationRequired: [
      'Proof of entertainment earnings history (W-2s, 1099s, or union cards: SAG-AFTRA, IATSE, AEA, AFM)',
      'Itemized documentation of crisis need (lease, past-due rent notice, medical bills, utility statements)',
      'Most recent bank statements showing shortfall'
    ],
    referralRequirement: 'None (apply directly through social services intake)',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'Demonstrated crisis financial need',
    employmentDependency: 'Performing arts and entertainment industry work history',
    applicationWindow: 'Ongoing crisis evaluation',
    whatCanBlockAccess: [
      'Requires documented entertainment industry work/earnings history',
      'Takes 1–2 weeks for social services casework review',
      'Direct vendor disbursement required for housing and utilities'
    ],
    accessFrictions: ['APPLICATION_REQUIRED', 'EMPLOYMENT_PROOF', 'NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED'],
    whatToDoNext: 'Submit an online intake application through entertainmentcommunity.org/services-and-programs/emergency-financial-assistance and upload your entertainment earnings proof.',
    howToApply: 'Apply online at entertainmentcommunity.org.',
    sourceUrl: 'https://entertainmentcommunity.org/services-and-programs/emergency-financial-assistance',
    primaryAuthoritativeSource: 'Entertainment Community Fund Social Services Standards',
    lastReviewedDate: '2026-08-20',
    dateLastVerified: '2026-08-20',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: 'Filed under arts and entertainment charities rather than domestic crisis relief finders.',
    workaround: 'Covers non-performers too: technicians, grips, camera operators, stagehands, hair/makeup stylists, front-of-house staff, and administrative workers across film, television, theatre, dance, and music with 3–5 years documented industry earnings.',
    accessNotes: 'Submit online social services intake with W-2/1099 industry tax forms or union cards (SAG-AFTRA, IATSE, Actors\' Equity).'
  },
  {
    id: 'nurses-house-emergency-grants',
    name: 'Nurses House Emergency Hardship Grants',
    organization: 'Nurses House, Inc.',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'INDUSTRY_EMERGENCY_FUNDS',
    barrierCategories: ['industry-hardship', 'rent-deposit', 'medical-dental', 'money-now'],
    matchTags: ['HEALTHCARE', 'NURSE', 'RN', 'RENT', 'HOUSING', 'MEDICAL', 'NO_POLICE_REPORT', 'NO_SHELTER_STAY'],
    whatItCanHelpWith: 'Provides emergency financial grants for housing expenses (rent or mortgage), utilities, and medical costs to Registered Nurses facing catastrophic emergency, trauma, domestic violence escape, or acute health crises.',
    whatItActuallyProvides: 'Direct grant payments disbursed to landlords, mortgage lenders, utility companies, or medical providers.',
    assistanceShapes: ['DIRECT_CASH', 'VENDOR_PAYMENT', 'RENT', 'UTILITY_PAYMENT', 'MEDICAL'],
    paymentMethod: 'DIRECT_TO_VENDOR',
    typicalAmount: '$1,000 to $2,500 based on verified monthly housing and living expense deficits',
    knownFundingLimits: 'Paid directly to housing and utility creditors; maximum funding caps apply per applicant lifetime',
    eligibility: 'Must be an actively licensed or recently practicing Registered Nurse (RN) experiencing an acute financial crisis, catastrophic displacement, or domestic emergency.',
    documentationRequired: [
      'Copy of current or recently active state RN license',
      'Proof of catastrophic emergency or loss of earnings (medical notes, advocate statements, lease agreement)',
      'Itemized monthly bills (lease agreement, mortgage statement, utility bills)'
    ],
    referralRequirement: 'None (direct nurse self-application)',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'Demonstrated immediate financial hardship',
    employmentDependency: 'Registered Nurse (RN) credentials',
    applicationWindow: 'Ongoing crisis intake',
    whatCanBlockAccess: [
      'Restricted to Registered Nurses (RNs) — does not currently cover LPNs or CNAs under general fund',
      'Requires valid RN license verification',
      'Vendor-direct payment structure for housing and utilities'
    ],
    accessFrictions: ['APPLICATION_REQUIRED', 'EMPLOYMENT_PROOF', 'NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED'],
    whatToDoNext: 'Complete the grant application at nurseshouse.org and upload your RN license number, lease/mortgage statement, and hardship summary.',
    howToApply: 'Apply online at nurseshouse.org/grants/.',
    sourceUrl: 'https://www.nurseshouse.org/grants/',
    primaryAuthoritativeSource: 'Nurses House 501(c)(3) Operating Charter',
    lastReviewedDate: '2026-08-21',
    dateLastVerified: '2026-08-21',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: 'Specialized 501(c)(3) dedicated strictly to Registered Nurses.',
    workaround: 'Provides fast housing and medical hardship grants for RNs facing acute crisis, health emergencies, domestic violence escape, or disaster displacement.',
    accessNotes: 'Apply at nurseshouse.org with copy of active or recently active RN license, brief hardship summary, and lease/landlord contact.'
  },
  {
    id: 'trade-union-benevolent-funds',
    name: 'Trade Union Emergency Hardship & Benevolent Funds',
    organization: 'AFL-CIO / Building & Construction Trades Union Locals',
    state: 'US',
    geography: 'Nationwide (Union Locals across US & Texas)',
    scope: 'NATIONWIDE',
    category: 'INDUSTRY_EMERGENCY_FUNDS',
    barrierCategories: ['industry-hardship', 'money-now', 'rent-deposit'],
    matchTags: ['UNION', 'TRADES', 'CONSTRUCTION', 'ELECTRICIAN', 'LABORER', 'CARPENTER', 'PLUMBER', 'CASH', 'NO_POLICE_REPORT'],
    whatItCanHelpWith: 'Provides confidential emergency hardship grants, dues waivers, and member-assistance micro-aid through local trade union halls (IBEW, LiUNA, UBC, SMART, Teamsters, USW) for members experiencing domestic catastrophe or sudden displacement.',
    whatItActuallyProvides: 'Direct financial assistance checks disbursed from Business Manager Discretionary Funds or local relief committees.',
    assistanceShapes: ['DIRECT_CASH', 'VENDOR_PAYMENT'],
    paymentMethod: 'SURVIVOR_DIRECT',
    typicalAmount: '$500 to $2,000 at the discretion of the Local Business Manager or Executive Board',
    knownFundingLimits: 'Governed by local union hall bylaws and benevolent fund balance',
    eligibility: 'Must be an active member in good standing (or qualifying retired member/dependent) of a recognized trade union local.',
    documentationRequired: [
      'Union card or member ID number verifying good standing',
      'Confidential request letter or interview with Shop Steward / Business Agent'
    ],
    referralRequirement: 'Union Shop Steward or Business Manager contact',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'None (union membership dependent)',
    employmentDependency: 'Union trades member in good standing',
    applicationWindow: 'Immediate local review',
    whatCanBlockAccess: [
      'Restricted to union members in good standing',
      'Requires speaking directly with a local union representative'
    ],
    accessFrictions: ['EMPLOYMENT_PROOF', 'NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED'],
    whatToDoNext: 'Contact your local union hall Business Agent or Shop Steward directly. Request a confidential consultation regarding the local\'s emergency relief or benevolent fund.',
    howToApply: 'Contact your local union hall Shop Steward or Business Agent.',
    sourceUrl: 'https://aflcio.org/community-services',
    primaryAuthoritativeSource: 'AFL-CIO Community Services Department Standards',
    lastReviewedDate: '2026-08-18',
    dateLastVerified: '2026-08-18',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: 'Internal fraternal benefits governed by local union bylaws; not publicly searchable or aggregated in 211 databases.',
    workaround: 'Local business managers have discretionary authority to release confidential hardship checks or waive dues during catastrophic family crisis.',
    accessNotes: 'Contact your local union hall Business Agent or Shop Steward directly and request a confidential emergency relief petition.'
  },
  {
    id: 'dod-transitional-compensation',
    name: 'DoD Transitional Compensation for Abused Dependents (10 U.S.C. § 1059)',
    organization: 'U.S. Department of Defense',
    state: 'US',
    geography: 'Nationwide (Military Installations & Worldwide)',
    scope: 'NATIONWIDE',
    category: 'LEGAL_PROTECTIONS',
    barrierCategories: ['statutory-rights', 'money-now', 'medical-dental'],
    matchTags: ['MILITARY', 'VETERAN', 'DEPENDENT', 'STATUTE', 'MONTHLY_INCOME', 'TRICARE', 'COMMISSARY', 'LEGAL'],
    whatItCanHelpWith: 'Provides statutory monthly financial payments (up to 36 months), full commissary and exchange shopping privileges, and TRICARE healthcare benefits to spouses and dependents of active-duty service members separated for dependent-abuse offenses.',
    whatItActuallyProvides: 'Monthly cash benefit payments set by law (equivalent to Dependency and Indemnity Compensation rates), TRICARE medical coverage, and military installation access privileges.',
    assistanceShapes: ['DIRECT_CASH', 'MEDICAL', 'LEGAL_SERVICE'],
    paymentMethod: 'SURVIVOR_DIRECT',
    typicalAmount: 'Monthly payments ($1,400+ per month base + child allowances) for up to 36 months',
    knownFundingLimits: 'Statutory benefit mandated under 10 U.S.C. § 1059; forfeited if survivor remarries or cohabitates with abuser during benefit period',
    eligibility: 'Spouse or dependent child of an active-duty military member who is separated from active duty under a court-martial sentence or administrative discharge resulting from a dependent-abuse offense (domestic violence, child abuse).',
    documentationRequired: [
      'DD Form 2698 (Application for Transitional Compensation)',
      'Copy of court-martial convening order, military discharge paperwork, or administrative separation notice showing abuse basis',
      'Marriage certificate and children\'s birth certificates'
    ],
    referralRequirement: 'Family Advocacy Program (FAP) Victim Advocate or Staff Judge Advocate (SJA) office',
    shelterConnectionRequired: false,
    policeReportRequired: true,
    incomeRestriction: 'None (statutory federal entitlement)',
    employmentDependency: 'Service member spouse/dependent status',
    applicationWindow: 'Must be submitted while separation action is pending or within statutory window of discharge',
    whatCanBlockAccess: [
      'Service member must be formally separated/discharged for a qualifying dependent-abuse offense',
      'Benefits terminate if survivor remarries or cohabitates with the abuser',
      'Requires military FAP or SJA processing'
    ],
    accessFrictions: ['APPLICATION_REQUIRED', 'PROTECTIVE_ORDER_REQUIRED'],
    whatToDoNext: 'Contact the installation Family Advocacy Program (FAP) Victim Advocate or Staff Judge Advocate (SJA) at the nearest military base to submit DD Form 2698.',
    howToApply: 'Contact installation Family Advocacy Program (FAP) or SJA office and submit DD Form 2698.',
    sourceUrl: 'https://www.militaryonesource.mil/family-relationships/relationships/domestic-abuse/transitional-compensation-program/',
    primaryAuthoritativeSource: '10 U.S.C. § 1059 / DoD Instruction 1342.24',
    lastReviewedDate: '2026-08-26',
    dateLastVerified: '2026-08-26',
    verificationStatus: 'OFFICIAL_SOURCE_CHECKED',
    isStatutoryRight: true,
    statuteCitation: '10 U.S.C. § 1059',
    whyMissed: 'Military administrative law benefit that civilian victim advocates and municipal helplines rarely understand or know how to trigger.',
    workaround: 'Dependents of active-duty service members administratively discharged or court-martialed for dependent-abuse offenses are legally entitled to up to 36 months of tax-free monthly compensation payments, commissary privileges, and TRICARE healthcare.',
    accessNotes: 'Contact the base Family Advocacy Program (FAP) Victim Advocate or Staff Judge Advocate (SJA) office. Submit DD Form 2698.'
  },
  {
    id: 'vfw-unmet-needs-grant',
    name: 'VFW Unmet Needs Emergency Financial Grant',
    organization: 'Veterans of Foreign Wars (VFW)',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'INDUSTRY_EMERGENCY_FUNDS',
    barrierCategories: ['military-veteran', 'rent-deposit', 'utility-deposit', 'transportation-gas'],
    matchTags: ['MILITARY', 'VETERAN', 'ACTIVE_DUTY', 'RENT', 'UTILITY', 'AUTO_REPAIR', 'NO_POLICE_REPORT', 'NO_SHELTER_STAY'],
    whatItCanHelpWith: 'Provides emergency financial grants of up to $1,500 for critical basic needs (rent, mortgage, electric/gas utilities, vehicle repairs, medical bills, and food) to eligible military service members, recent veterans, and their families.',
    whatItActuallyProvides: 'Direct creditor payments made on the veteran/service member\'s behalf to landlords, utility companies, or mechanics.',
    assistanceShapes: ['VENDOR_PAYMENT', 'RENT', 'UTILITY_PAYMENT', 'CAR_REPAIR'],
    paymentMethod: 'DIRECT_TO_VENDOR',
    typicalAmount: 'Up to $1,500 in direct creditor bill payments',
    knownFundingLimits: 'Max $1,500 per family per 18-month cycle; paid directly to verified creditors',
    eligibility: 'Must be an active-duty service member, reservist/guard member, or veteran with an honorable discharge within the past 72 months (or service-connected disability), experiencing sudden financial emergency.',
    documentationRequired: [
      'DD-214 or current military orders / LES verifying service tenure',
      'Past-due lease, mortgage statement, utility bill, or itemized mechanic repair estimate',
      'Brief explanation of unforeseen financial emergency'
    ],
    referralRequirement: 'None (direct online application)',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'Demonstrated financial deficit due to military transition or deployment',
    employmentDependency: 'Military / Veteran service tenure',
    applicationWindow: 'Within 72 months of military discharge or ongoing active duty',
    whatCanBlockAccess: [
      'Discharge must be within the last 72 months (unless service-connected disability)',
      'Paid directly to creditors — no cash disbursed to applicant',
      'Processing time takes 10–14 business days'
    ],
    accessFrictions: ['APPLICATION_REQUIRED', 'NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED'],
    whatToDoNext: 'Apply online at vfw.org/assistance/financial-grants. Upload your DD-214 and itemized creditor bills.',
    howToApply: 'Apply online at vfw.org/assistance/financial-grants.',
    sourceUrl: 'https://www.vfw.org/assistance/financial-grants',
    primaryAuthoritativeSource: 'Veterans of Foreign Wars Unmet Needs Program Guidelines',
    lastReviewedDate: '2026-08-24',
    dateLastVerified: '2026-08-24',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: 'Veteran organization relief fund that civilian DV navigators rarely query for family crisis relief.',
    workaround: 'Grants of up to $1,500 for emergency rent, utilities, food, auto repairs, or transportation for service members on active duty, deployed, or discharged within the past 72 months. Paid directly to creditors.',
    accessNotes: 'Apply online at vfw.org/assistance/financial-grants with DD-214, military orders, and itemized billing statements.'
  },
  {
    id: 'operation-homefront-cfa',
    name: 'Operation Homefront Critical Financial Assistance (CFA)',
    organization: 'Operation Homefront',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'INDUSTRY_EMERGENCY_FUNDS',
    barrierCategories: ['military-veteran', 'rent-deposit', 'utility-deposit', 'transportation-gas'],
    matchTags: ['MILITARY', 'ENLISTED', 'E1_E6', 'VETERAN', 'RENT', 'AUTO_REPAIR', 'RELOCATION', 'NO_POLICE_REPORT'],
    whatItCanHelpWith: 'Provides critical financial grants for past-due mortgage/rent payments, critical auto repairs, essential utilities, emergency food, and moving costs for junior enlisted military families and wounded veterans.',
    whatItActuallyProvides: 'Direct vendor grant payments to landlords, mortgage servicers, utility providers, and licensed auto repair shops.',
    assistanceShapes: ['VENDOR_PAYMENT', 'RENT', 'CAR_REPAIR', 'MOVING', 'UTILITY_PAYMENT'],
    paymentMethod: 'DIRECT_TO_VENDOR',
    typicalAmount: '$800 to $2,500 in direct creditor bill settlements',
    knownFundingLimits: 'Paid strictly to verified third-party creditors; case-by-case evaluation',
    eligibility: 'Must be active duty military ranked E-1 through E-6, or post-9/11 wounded, ill, or injured veteran (any rank). Must demonstrate immediate financial hardship.',
    documentationRequired: [
      'Current military LES or DD-214 + VA disability rating documentation',
      'Itemized bills requiring payment (lease agreement, mechanic estimate, utility bill)',
      'Proof of household income shortfall'
    ],
    referralRequirement: 'None (direct online application)',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'Demonstrated emergency hardship',
    employmentDependency: 'Active duty rank E-1 to E-6 or post-9/11 wounded veteran',
    applicationWindow: 'Ongoing crisis intake',
    whatCanBlockAccess: [
      'Restricted to rank E-1 through E-6 for non-wounded active duty',
      'Requires documented third-party invoice/lease',
      'Processing averages 5–10 business days'
    ],
    accessFrictions: ['APPLICATION_REQUIRED', 'NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED'],
    whatToDoNext: 'Apply online at operationhomefront.org and submit your LES or DD-214 along with your creditor invoices.',
    howToApply: 'Apply online at operationhomefront.org/critical-financial-assistance/.',
    sourceUrl: 'https://operationhomefront.org/critical-financial-assistance/',
    primaryAuthoritativeSource: 'Operation Homefront CFA Operating Standards',
    lastReviewedDate: '2026-08-23',
    dateLastVerified: '2026-08-23',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: 'Military family support charity not indexed in municipal resource finders.',
    workaround: 'Designed specifically for enlisted ranks E-1 through E-6 (and post-9/11 wounded veterans). Covers direct mortgage/rent payments, auto repair bills, essential home repairs, and relocation moving expenses.',
    accessNotes: 'Apply online at operationhomefront.org with current military LES, landlord contact, and repair estimates.'
  },
  {
    id: 'hud-vawa-emergency-transfer',
    name: 'HUD VAWA Emergency Transfer Plans & Housing Portability (24 CFR § 5.2005(e))',
    organization: 'U.S. Department of Housing and Urban Development (HUD)',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'LEGAL_PROTECTIONS',
    barrierCategories: ['statutory-rights', 'rent-deposit', 'lease-escape'],
    matchTags: ['HUD', 'SECTION_8', 'VOUCHER', 'HOUSING_AUTHORITY', 'PUBLIC_HOUSING', 'LIHTC', 'STATUTE', 'PORTABILITY', 'NO_POLICE_REPORT'],
    whatItCanHelpWith: 'Establishes a statutory federal right for survivors of domestic violence, dating violence, sexual assault, or stalking living in HUD-assisted housing to request an immediate emergency transfer to another safe unit or port their Housing Choice Voucher across county/state lines without lease termination penalties.',
    whatItActuallyProvides: 'Statutory transfer entitlement, expedited voucher portability, and protection from eviction or voucher forfeiture.',
    assistanceShapes: ['LEGAL_SERVICE', 'RENT', 'DOCUMENT_REPLACEMENT'],
    paymentMethod: 'STATUTORY_RIGHT',
    typicalAmount: 'Full retention and portability of subsidized housing assistance',
    knownFundingLimits: 'Statutory mandate applying to all covered housing providers (Housing Choice Voucher, Public Housing, Project-Based Section 8, Section 202, Section 811, HOME, LIHTC)',
    eligibility: 'Must be a tenant in a covered HUD housing program who reasonably believes there is a threat of imminent harm from further violence if they remain in the dwelling unit.',
    documentationRequired: [
      'HUD Model Form 5383 (Emergency Transfer Request for Certain Victims of Domestic Violence)',
      'Self-certification statement using HUD Form 5382 OR advocate/medical/legal affidavit'
    ],
    referralRequirement: 'Self-invoke with property manager or Housing Authority caseworker',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'Existing HUD housing tenant',
    employmentDependency: 'None',
    applicationWindow: 'Immediate upon imminent safety threat',
    whatCanBlockAccess: [
      'Applies only to federally subsidized housing programs (Section 8, Public Housing, LIHTC)',
      'Housing authorities may face waitlists for internal safe units, but voucher portability must be expedited',
      'Requires formal submission of HUD Form 5383'
    ],
    accessFrictions: ['NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED'],
    whatToDoNext: 'Download HUD Model Form 5383 and submit it directly to your housing authority caseworker or subsidized property manager. Request expedited voucher portability.',
    howToApply: 'Submit HUD Form 5383 to your local Public Housing Authority (PHA) or property manager.',
    sourceUrl: 'https://www.hud.gov/program_offices/housing/mfh/vawa',
    primaryAuthoritativeSource: '24 CFR § 5.2005(e) / HUD VAWA Final Rule',
    lastReviewedDate: '2026-08-27',
    dateLastVerified: '2026-08-27',
    verificationStatus: 'OFFICIAL_SOURCE_CHECKED',
    isStatutoryRight: true,
    statuteCitation: '24 CFR § 5.2005(e)',
    whyMissed: 'Public housing tenants and Section 8 voucher holders are often falsely told that moving before their lease expires will result in permanent forfeiture of their housing assistance voucher.',
    workaround: 'Under VAWA 2022 federal law (24 CFR § 5.2005(e)), any tenant in covered housing (Section 8, Housing Choice Voucher, Public Housing, Project-Based Section 8, LIHTC) who reasonably fears imminent harm has a statutory right to an emergency transfer. The Public Housing Authority (PHA) must allow the voucher to be ported immediately across city/county/state lines without terminating assistance.',
    accessNotes: 'Submit HUD Model Form 5383 (Emergency Transfer Request) or written statement to housing authority or property management. Does not require a police report.'
  },
  {
    id: 'ssa-number-change-dv',
    name: 'SSA Social Security Number Change for Domestic Violence Survivors',
    organization: 'Social Security Administration (SSA)',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'LEGAL_PROTECTIONS',
    barrierCategories: ['statutory-rights', 'identity-coerced-debt', 'device-car-tracking'],
    matchTags: ['SSA', 'SSN', 'IDENTITY', 'STALKING', 'CREDIT', 'PRIVACY', 'LEGAL', 'STATUTE'],
    whatItCanHelpWith: 'Authorizes the assignment of a brand-new Social Security Number (SSN) to a survivor of severe domestic violence, stalking, or harassment when an abuser is actively using the existing number to locate, harass, or inflict financial injury.',
    whatItActuallyProvides: 'A completely new, clean Social Security Number issued by the federal government with cross-reference confidentiality.',
    assistanceShapes: ['DOCUMENT_REPLACEMENT', 'LEGAL_INFORMATION'],
    paymentMethod: 'NON_MONETARY_SERVICE',
    typicalAmount: 'Free official federal identity reissuance',
    knownFundingLimits: 'Administrative federal remedy under SSA POMS RM 10225.060',
    eligibility: 'Must provide third-party evidence documenting ongoing harassment, stalking, or severe physical danger linked to the abuser\'s knowledge of the existing SSN.',
    documentationRequired: [
      'Form SS-5 (Application for a Social Security Card)',
      'Primary identity documents (certified U.S. birth certificate, passport, state photo ID)',
      'Third-party corroborating evidence: police reports, court restraining orders, medical records, or detailed letters from domestic violence shelter advocates'
    ],
    referralRequirement: 'In-person SSA Field Office interview with documentation packet',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'None',
    employmentDependency: 'None',
    applicationWindow: 'Ongoing administrative evaluation',
    whatCanBlockAccess: [
      'High evidentiary threshold: requires third-party proof of ongoing danger or abuser misuse of old SSN',
      'Does not erase previous tax, child support, or criminal liabilities',
      'Credit history starts as a blank file; credit score must be built from scratch'
    ],
    accessFrictions: ['APPLICATION_REQUIRED', 'IDENTITY_DOCUMENTS', 'WALK_IN'],
    whatToDoNext: 'Gather your identity documents and third-party evidence packet. Make an in-person appointment at your local Social Security Administration Field Office and request an SSN change under POMS RM 10225.060.',
    howToApply: 'Schedule an appointment at a local SSA Field Office with Form SS-5 and evidence packet.',
    sourceUrl: 'https://secure.ssa.gov/poms.nsf/lnx/0110225060',
    primaryAuthoritativeSource: 'Social Security Administration POMS RM 10225.060',
    lastReviewedDate: '2026-08-25',
    dateLastVerified: '2026-08-25',
    verificationStatus: 'OFFICIAL_SOURCE_CHECKED',
    isStatutoryRight: true,
    statuteCitation: 'SSA POMS RM 10225.060',
    whyMissed: 'SSA does not advertise this route publicly on general consumer pages; it is an internal administrative procedure governed by POMS RM 10225.060.',
    workaround: 'While SSA generally prohibits changing SSNs, POMS RM 10225.060 explicitly authorizes assignment of a brand-new Social Security Number when evidence proves an abuser or stalker is using the existing SSN to locate, harass, or inflict financial ruin.',
    accessNotes: 'Schedule in-person appointment at local SSA Field Office. Bring Form SS-5, birth certificate/passport, and third-party corroborating documentation (protective orders, advocate letters, or medical records). Note: Credit bureaus create a new file; previous credit history does not automatically carry over.'
  },
  {
    id: 'freefrom-coerced-debt-toolkit',
    name: 'FreeFrom Coerced Debt Dispute Toolkit & Economic Resources',
    organization: 'FreeFrom (National Center for Economic Security)',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'LEGAL_PROTECTIONS',
    barrierCategories: ['identity-coerced-debt', 'money-now'],
    matchTags: ['COERCED_DEBT', 'CREDIT', 'IDENTITY_THEFT', 'FRAUD', 'DISPUTE', 'LEGAL_INFORMATION', 'NO_POLICE_REPORT'],
    whatItCanHelpWith: 'Provides free legal dispute letter generators and structured self-advocacy tools for survivors to contest, block, and discharge debts (credit cards, vehicle loans, utility bills, and personal loans) incurred through intimate partner coercion or identity theft.',
    whatItActuallyProvides: 'State-specific legal dispute letter generators, credit bureau dispute packets, and economic safety planning tools.',
    assistanceShapes: ['LEGAL_INFORMATION', 'DOCUMENT_REPLACEMENT', 'DEBT_ASSISTANCE'],
    paymentMethod: 'NON_MONETARY_SERVICE',
    typicalAmount: 'Free web-based legal self-advocacy toolkit',
    knownFundingLimits: 'Non-monetary legal resource; provides dispute tools rather than cash grant payoffs',
    eligibility: 'Any survivor experiencing credit destruction, collections harassment, or fraudulent debt incurred through coercion, duress, or fraud by an intimate partner.',
    documentationRequired: [
      'Credit reports (from AnnualCreditReport.com) showing disputed trade lines',
      'Collection notices or loan account statements',
      'Brief factual narrative of coercion (police report NOT strictly required under civil FCRA rules)'
    ],
    referralRequirement: 'None (direct web access)',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'None',
    employmentDependency: 'None',
    applicationWindow: 'Immediate online access',
    whatCanBlockAccess: [
      'Self-directed process requiring survivor to mail dispute packets via certified mail',
      'Creditors may dispute initial claims without persistent follow-up'
    ],
    accessFrictions: ['NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED', 'ONLINE_APPLICATION'],
    whatToDoNext: 'Visit freefrom.org, pull your free credit reports, and use the Coerced Debt Toolkit to generate formal dispute letters to credit bureaus and collection agencies.',
    howToApply: 'Access the free dispute generator at freefrom.org.',
    sourceUrl: 'https://www.freefrom.org/resources/coerced-debt-toolkit/',
    primaryAuthoritativeSource: 'FreeFrom National Survivor Economic Security Standards',
    lastReviewedDate: '2026-08-26',
    dateLastVerified: '2026-08-26',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: 'Civil/consumer rights tool for debt cancellation rather than traditional financial charity.',
    workaround: 'Offers state-specific statutory legal templates to dispute debt forced by an abuser (credit cards, vehicle loans, utility contracts, medical debt) under the Fair Credit Reporting Act (FCRA), Fair Debt Collection Practices Act (FDCPA), and state coerced-debt laws without having to hire a private attorney.',
    accessNotes: 'Visit freefrom.org to generate custom debt-dispute letters to send directly to credit bureaus and collection agencies.'
  },
  {
    id: 'airguard-ble-tracker-detection',
    name: 'AirGuard & BLE Bluetooth Tracker Detection Utilities',
    organization: 'Technical University of Darmstadt (Secure Mobile Networking Lab)',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'DIGITAL_DEVICE_SAFETY',
    barrierCategories: ['device-car-tracking', 'phone-controlled'],
    matchTags: ['TRACKER', 'AIRTAG', 'TILE', 'SMARTTAG', 'BLUETOOTH', 'VEHICLE_TRACKING', 'STALKERWARE', 'DIGITAL_SAFETY'],
    whatItCanHelpWith: 'Detects unauthorized Bluetooth tracking devices (Apple AirTags, Samsung SmartTags, Tile trackers, and Chipolo devices) hidden on vehicles, clothing, or personal belongings without alerting the tracker owner.',
    whatItActuallyProvides: 'Free privacy utility application for Android and iOS that performs automated passive background scans and precise proximity signal analysis.',
    assistanceShapes: ['DEVICE_SAFETY', 'LEGAL_INFORMATION'],
    paymentMethod: 'NON_MONETARY_SERVICE',
    typicalAmount: 'Free open-source privacy software',
    knownFundingLimits: 'Unlimited free access',
    eligibility: 'Anyone with an Android or iOS smartphone concerned about physical tracking or stalking.',
    documentationRequired: ['None'],
    referralRequirement: 'None',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'None',
    employmentDependency: 'None',
    applicationWindow: 'Immediate download',
    whatCanBlockAccess: [
      'Requires Bluetooth and Location permissions enabled on smartphone for beacon detection',
      'Tracker must be actively transmitting Bluetooth LE advertisements'
    ],
    accessFrictions: ['NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED'],
    whatToDoNext: 'Install AirGuard from Google Play Store or F-Droid (or Apple App Store). Enable background protection and run a manual scan when stationary away from your primary residence.',
    howToApply: 'Download free from Google Play Store or F-Droid.',
    sourceUrl: 'https://github.com/seemoo-lab/AirGuard',
    primaryAuthoritativeSource: 'TU Darmstadt Secure Mobile Networking Lab Privacy Research',
    lastReviewedDate: '2026-08-24',
    dateLastVerified: '2026-08-24',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: 'Open-source academic security research software not indexed in social service directories.',
    workaround: 'Actively scans for and locates hidden AirTags, Tile devices, Samsung SmartTags, and generic Bluetooth LE beacons following your vehicle or person, operating on both Android and iOS without triggering audible chirps that alert the tracker owner prematurely.',
    accessNotes: 'Download free via Google Play Store, F-Droid, or Apple App Store. Enable background protection to receive silent alerts when an unknown beacon is traveling with you.'
  },
  {
    id: 'uscis-vawa-self-petition',
    name: 'USCIS VAWA Self-Petition (Form I-360 Independent Legal Status)',
    organization: 'U.S. Citizenship and Immigration Services (USCIS)',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'LEGAL_PROTECTIONS',
    barrierCategories: ['statutory-rights', 'immigration-legal'],
    matchTags: ['IMMIGRATION', 'VAWA', 'I360', 'GREEN_CARD', 'WORK_PERMIT', 'STATUTE', 'NO_POLICE_REPORT'],
    whatItCanHelpWith: 'Provides an independent, confidential statutory pathway for non-citizen spouses, children, or parents who have suffered battery or extreme cruelty by a U.S. Citizen or Lawful Permanent Resident (LPR) to obtain lawful permanent residency and work authorization without the abuser\'s knowledge or participation.',
    whatItActuallyProvides: 'Approved immigrant classification (Form I-360), Employment Authorization Document (EAD work permit), and pathway to Adjustment of Status (Green Card).',
    assistanceShapes: ['LEGAL_SERVICE', 'DOCUMENT_REPLACEMENT'],
    paymentMethod: 'STATUTORY_RIGHT',
    typicalAmount: 'Confidential immigration self-petition (Form I-360 has $0 filing fee for VAWA)',
    knownFundingLimits: 'Statutory immigration benefit under 8 U.S.C. § 1154(a)(1); protected by strict statutory non-disclosure laws (8 U.S.C. § 1367)',
    eligibility: 'Must be the spouse, child, or parent of an abusive U.S. Citizen or LPR, have resided with the abuser, and demonstrated battery or extreme cruelty during the qualifying relationship.',
    documentationRequired: [
      'Form I-360 (Petition for Amerasian, Widow(er), or Special Immigrant)',
      'Proof of abuser\'s citizenship or LPR status (birth certificate, passport, green card copy, or FOIA request)',
      'Marriage certificate showing good-faith marriage (for spouse petitions)',
      'Corroborating evidence of abuse (affidavits, police/court records, shelter letters, medical records, or psychological evaluations)'
    ],
    referralRequirement: 'DOJ-accredited legal representative or immigration attorney recommended',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'None (Form I-360 has zero filing fee)',
    employmentDependency: 'None',
    applicationWindow: 'Within 2 years of divorce if marriage was terminated due to abuse',
    whatCanBlockAccess: [
      'Abuser must be a U.S. Citizen or Lawful Permanent Resident (LPR)',
      'If divorced, petition must be filed within 2 years of divorce decree',
      'Processing times at USCIS Vermont Service Center average 24–36 months'
    ],
    accessFrictions: ['APPLICATION_REQUIRED', 'NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED'],
    whatToDoNext: 'Contact an accredited non-profit immigration legal service (e.g. American Gateways in Central Texas, Catholic Charities, NIWAP) to prepare and file Form I-360 with a safe mailing address.',
    howToApply: 'File Form I-360 with the USCIS Vermont Service Center (designated VAWA unit).',
    sourceUrl: 'https://www.uscis.gov/humanitarian/battered-spouse-children-and-parents',
    primaryAuthoritativeSource: '8 U.S.C. § 1154(a)(1) / USCIS Policy Manual Vol. 3',
    lastReviewedDate: '2026-08-27',
    dateLastVerified: '2026-08-27',
    verificationStatus: 'OFFICIAL_SOURCE_CHECKED',
    isStatutoryRight: true,
    statuteCitation: '8 U.S.C. § 1154(a)(1)',
    whyMissed: 'Abusers frequently threaten immigrant spouses and children with immediate deportation if they leave or seek assistance.',
    workaround: 'Federal statutory protection (8 U.S.C. § 1154(a)(1)(A)) allows abused non-citizen spouses, children, and parents of US Citizens or Lawful Permanent Residents (LPRs) to petition for permanent residency completely independently. Strict confidentiality protections under 8 U.S.C. § 1367 forbid USCIS from notifying or sharing information with the abusive sponsor.',
    accessNotes: 'Connect with a DOJ-accredited immigration legal clinic (e.g. American Gateways in Central Texas, Catholic Charities, NIWAP). File Form I-360 with USCIS Vermont Service Center. Includes fee waiver eligibility and work authorization (Form I-765).'
  },
  {
    id: 'u-visa-t-visa-remedies',
    name: 'U Visa & T Visa Nonimmigrant Status (Crime Victims & Human Trafficking)',
    organization: 'U.S. Department of Homeland Security / USCIS',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'LEGAL_PROTECTIONS',
    barrierCategories: ['statutory-rights', 'immigration-legal'],
    matchTags: ['IMMIGRATION', 'U_VISA', 'T_VISA', 'TRAFFICKING', 'WORK_AUTHORIZATION', 'LEGAL', 'STATUTE'],
    whatItCanHelpWith: 'Provides nonimmigrant legal status, Employment Authorization Documents (EAD work permits), and a pathway to Lawful Permanent Residency for immigrant survivors of qualifying violent crimes (U Visa) or commercial sex/labor trafficking (T Visa).',
    whatItActuallyProvides: '4-year nonimmigrant legal status, deportation protection, work permit, and permanent residency eligibility.',
    assistanceShapes: ['LEGAL_SERVICE', 'DOCUMENT_REPLACEMENT'],
    paymentMethod: 'STATUTORY_RIGHT',
    typicalAmount: 'Statutory legal protection with fee waivers available',
    knownFundingLimits: 'Annual statutory cap of 10,000 U Visas (Bona Fide Determination provides interim work authorization while awaiting visa availability)',
    eligibility: 'U Visa: Victim of qualifying crime (domestic violence, felony assault, stalking) who has been helpful in investigation/prosecution. T Visa: Victim of severe commercial sex or labor trafficking who complies with reasonable law enforcement requests.',
    documentationRequired: [
      'Form I-918 (U Visa) or Form I-914 (T Visa)',
      'For U Visa: Form I-918 Supplement B (Law Enforcement Certification signed by police, prosecutor, or judge)',
      'Detailed personal declaration and corroborating medical/police/advocate evidence'
    ],
    referralRequirement: 'DOJ-accredited legal aid organization or immigration attorney',
    shelterConnectionRequired: false,
    policeReportRequired: true,
    incomeRestriction: 'None (fee waivers available for all associated forms)',
    employmentDependency: 'None',
    applicationWindow: 'Ongoing statutory evaluation',
    whatCanBlockAccess: [
      'U Visa requires signed law enforcement certification (Form I-918 Supplement B)',
      'USCIS processing backlog is significant, though Bona Fide Determinations provide interim work authorization',
      'Requires experienced immigration legal representation'
    ],
    accessFrictions: ['APPLICATION_REQUIRED', 'POLICE_REPORT_REQUIRED'],
    whatToDoNext: 'Consult with an accredited non-profit immigration legal clinic to evaluate crime victimization facts and request law enforcement certification.',
    howToApply: 'Submit Form I-918 or I-914 through accredited legal counsel to USCIS.',
    sourceUrl: 'https://www.uscis.gov/humanitarian/victims-of-human-trafficking-and-other-crimes',
    primaryAuthoritativeSource: '8 U.S.C. § 1101(a)(15)(U) & (T) / USCIS Policy Guidelines',
    lastReviewedDate: '2026-08-27',
    dateLastVerified: '2026-08-27',
    verificationStatus: 'OFFICIAL_SOURCE_CHECKED',
    isStatutoryRight: true,
    statuteCitation: '8 U.S.C. § 1101(a)(15)(U)',
    whyMissed: 'Complex statutory immigration relief requiring specific law enforcement certification or trafficking evidence.',
    workaround: 'Provides 4 years of lawful nonimmigrant status, Employment Authorization Documents (EAD), and a path to permanent residency for survivors of qualifying violent crimes (U Visa / Form I-918) or commercial sex/labor trafficking (T Visa / Form I-914). Bona Fide Determination policies provide interim work authorization while petitions are pending.',
    accessNotes: 'Seek screening from accredited immigration legal aid providers. U Visa requires Form I-918 Supplement B signed by a certifying law enforcement or judicial agency.'
  },
  {
    id: 'stronghearts-native-helpline',
    name: 'StrongHearts Native Helpline (Tribal Jurisdiction & Culturally-Centered Safety)',
    organization: 'StrongHearts Native Helpline',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'HOTLINES_CRISIS_HOUSING',
    barrierCategories: ['hotlines-safe-intake', 'statutory-rights', 'legal-aid'],
    matchTags: ['NATIVE_AMERICAN', 'INDIGENOUS', 'TRIBAL', 'VAWA_SDVCJ', 'HELPLINE', 'CULTURE', 'NO_POLICE_REPORT', 'NO_SHELTER_STAY'],
    whatItCanHelpWith: 'Provides 24/7 confidential, culturally tailored domestic and sexual violence navigation, emergency shelter coordination, and legal jurisdiction advocacy for Native American and Alaska Native survivors across reservation and urban communities.',
    whatItActuallyProvides: 'One-on-one confidential advocacy, safety planning, tribal resource navigation, and legal referral under tribal court and VAWA SDVCJ laws.',
    assistanceShapes: ['COUNSELING', 'LEGAL_INFORMATION'],
    paymentMethod: 'NON_MONETARY_SERVICE',
    typicalAmount: 'Free 24/7 confidential advocacy and tribal resource mapping',
    knownFundingLimits: 'Unlimited free confidential access',
    eligibility: 'Native American and Alaska Native survivors, family members, or service providers needing tribal legal/safety navigation.',
    documentationRequired: ['None (strictly confidential intake)'],
    referralRequirement: 'None (direct call/chat)',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'None',
    employmentDependency: 'None',
    applicationWindow: 'Immediate 24/7 access',
    whatCanBlockAccess: ['None'],
    accessFrictions: ['NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED', 'CALL_ONLY', 'SAME_DAY_POSSIBLE'],
    whatToDoNext: 'Call or text 1-844-7NATIVE (1-844-762-8483) or visit strongheartshelpline.org for 24/7 confidential chat with a Native advocate.',
    howToApply: 'Call or text 1-844-7NATIVE (1-844-762-8483) or chat at strongheartshelpline.org.',
    sourceUrl: 'https://strongheartshelpline.org/',
    primaryAuthoritativeSource: 'StrongHearts Native Helpline 501(c)(3) Operating Charter',
    lastReviewedDate: '2026-08-25',
    dateLastVerified: '2026-08-25',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: 'Specialized Indigenous-led resource omitted by municipal and county-level directories.',
    workaround: 'Confidential, culturally tailored 24/7 advocacy for Native American and Alaska Native survivors. Expertly navigates complex overlapping Tribal Court, State, and Federal jurisdictional boundaries under VAWA Special Domestic Violence Criminal Jurisdiction (SDVCJ) and Indian Civil Rights Act frameworks.',
    accessNotes: 'Call or text 1-844-7NATIVE (1-844-762-8483) or visit strongheartshelpline.org for 1-on-1 confidential chat.'
  },
  {
    id: 'face-to-face-reconstructive-surgery',
    name: 'FACE TO FACE: Domestic Violence Reconstructive Surgery',
    organization: 'American Academy of Facial Plastic and Reconstructive Surgery (AAFPRS Foundation)',
    state: 'US',
    geography: 'Nationwide',
    scope: 'NATIONWIDE',
    category: 'PHYSICAL_RESTORATION',
    barrierCategories: ['medical-dental', 'physical-restoration'],
    matchTags: ['SURGERY', 'MEDICAL', 'RECONSTRUCTIVE', 'FACIAL', 'PRO_BONO', 'PHYSICAL_RESTORATION', 'NO_POLICE_REPORT'],
    whatItCanHelpWith: 'Provides 100% pro bono facial plastic and reconstructive surgery to repair facial injuries, fractures, scars, and lacerations caused by domestic violence.',
    whatItActuallyProvides: 'Pro bono surgical care, operating room procedures, and post-operative medical management provided by board-certified facial plastic surgeons.',
    assistanceShapes: ['MEDICAL', 'OTHER'],
    paymentMethod: 'NON_MONETARY_SERVICE',
    typicalAmount: '100% free surgical care (hospital/anesthesia fees waived or covered through foundation)',
    knownFundingLimits: 'Pro bono surgical network operating nationwide',
    eligibility: 'Must have sustained physical facial injuries caused by domestic violence. Survivor must be out of the abusive relationship for at least 12 months and complete a counseling/advocate intake interview.',
    documentationRequired: [
      'Intake application through AAFPRS Foundation',
      'Referral letter from a domestic violence shelter advocate, licensed therapist, or social worker confirming at least 12 months of separation from the abuser',
      'Medical/dental records and facial injury photographs'
    ],
    referralRequirement: 'Shelter advocate, licensed therapist, or social worker referral letter',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'Cannot afford private reconstructive surgery or lack comprehensive medical coverage',
    employmentDependency: 'None',
    applicationWindow: 'At least 12 months following physical separation from abuser',
    whatCanBlockAccess: [
      'Requires 12 months of separation from the abusive partner to ensure physical safety and healing',
      'Requires advocate/therapist confirmation letter',
      'Surgical evaluation determines medical candidacy'
    ],
    accessFrictions: ['APPLICATION_REQUIRED', 'ADVOCATE_REFERRAL_REQUIRED', 'NO_POLICE_REPORT_REQUIRED'],
    whatToDoNext: 'Call 1-800-842-4546 or visit aafprs.org to request a FACE TO FACE intake application. Have your advocate or counselor submit a separation verification letter.',
    howToApply: 'Call 1-800-842-4546 or apply via aafprs.org.',
    sourceUrl: 'https://www.aafprs.org/AAFPRS/Community/Face_to_Face/Domestic_Violence.aspx',
    primaryAuthoritativeSource: 'AAFPRS Educational and Research Foundation Standards',
    lastReviewedDate: '2026-08-22',
    dateLastVerified: '2026-08-22',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: 'Pro bono surgical specialty network outside standard social service directories.',
    workaround: 'Provides 100% pro bono surgical repair of facial injuries, fractures, and lacerations caused by domestic violence.',
    accessNotes: 'Call 1-800-842-4546 or apply through AAFPRS Foundation with documentation from a licensed therapist or domestic violence shelter advocate confirming separation from the abusive partner for at least 12 months.'
  },
  {
    id: 'removery-ink-tattoo-removal',
    name: 'Removery INK Initiative (Forced-Branding & Human Trafficking Tattoo Removal)',
    organization: 'Removery Laser Tattoo Removal',
    state: 'US',
    geography: 'Nationwide (Studios across Texas & US)',
    scope: 'NATIONWIDE',
    category: 'PHYSICAL_RESTORATION',
    barrierCategories: ['physical-restoration', 'medical-dental'],
    matchTags: ['TATTOO_REMOVAL', 'BRANDING', 'TRAFFICKING', 'FORCED_MARKINGS', 'PRO_BONO', 'PHYSICAL_RESTORATION', 'NO_POLICE_REPORT'],
    whatItCanHelpWith: 'Provides 100% pro bono laser tattoo removal for survivors of domestic human trafficking, commercial sexual exploitation, or intimate partner coercive branding tattoos (names, barcodes, symbols, gang markings).',
    whatItActuallyProvides: 'Complete series of clinical PicoWay laser removal sessions at no cost until the tattoo is completely eliminated or safely lightened.',
    assistanceShapes: ['MEDICAL', 'OTHER'],
    paymentMethod: 'NON_MONETARY_SERVICE',
    typicalAmount: '100% free multi-session clinical laser tattoo removal',
    knownFundingLimits: 'Pro bono community initiative across all Removery studio locations in Texas (Austin, Dallas, Houston, San Antonio) and nationwide',
    eligibility: 'Anyone with forced-branding, human-trafficking, or intimate partner coercive tattoos seeking laser removal.',
    documentationRequired: [
      'Online application with clear photo of tattoo',
      'Brief intake statement confirming non-consensual branding or trafficking origin'
    ],
    referralRequirement: 'None (direct self-application or advocate referral)',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'None',
    employmentDependency: 'None',
    applicationWindow: 'Immediate rolling intake',
    whatCanBlockAccess: [
      'Requires physical travel to a Removery studio location (available across major Texas cities and nationwide)',
      'Multiple laser sessions spaced 6–8 weeks apart required for complete removal'
    ],
    accessFrictions: ['ONLINE_APPLICATION', 'NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED'],
    whatToDoNext: 'Visit removery.com/about/ink-initiative, fill out the short intake form, and upload a clear photo of the tattoo you need removed.',
    howToApply: 'Apply online at removery.com/about/ink-initiative/.',
    sourceUrl: 'https://removery.com/about/ink-initiative/',
    primaryAuthoritativeSource: 'Removery INK Community Initiative Standards',
    lastReviewedDate: '2026-08-24',
    dateLastVerified: '2026-08-24',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: 'Private clinical initiative that most non-profit and shelter intake coordinators do not know exists.',
    workaround: '100% free, confidential PicoWay laser tattoo removal for survivors of domestic human trafficking, commercial sexual exploitation, or intimate partner coercive branding. Available across dozens of Texas and nationwide studio locations (Austin, Dallas, Houston, San Antonio).',
    accessNotes: 'Apply online at removery.com/about/ink-initiative with a clear photo of the tattoo and brief intake details.'
  },
  {
    id: 'rural-ministerial-alliance-tx',
    name: 'Rural Central Texas Ministerial Alliance Discretionary Micro-Aid',
    organization: 'Central Texas Ecumenical Pastoral Alliances (Bastrop, Caldwell, Hays, Rural Travis)',
    state: 'TX',
    geography: 'Central Texas Rural Counties (Bastrop, Caldwell, Hays, East Travis)',
    scope: 'TEXAS_COUNTY',
    category: 'HYPERLOCAL_MICRO_AID',
    barrierCategories: ['rural-microaid', 'money-now', 'transportation-gas'],
    matchTags: ['TEXAS', 'RURAL', 'BASTROP', 'CALDWELL', 'HAYS', 'GAS_CARD', 'HOTEL_VOUCHER', 'BUS_TICKET', 'NO_POLICE_REPORT', 'NO_ID'],
    whatItCanHelpWith: 'Provides immediate discretionary micro-aid ($50–$300) for emergency fuel gas cards, 1–2 night roadside motel vouchers, prescription medication, and bus tickets in rural Central Texas communities without formal shelter facilities.',
    whatItActuallyProvides: 'Immediate prepaid gas cards, supermarket vouchers, roadside motel billing, or cash disbursements from pooled pastor checking accounts.',
    assistanceShapes: ['GAS_CARD', 'HOTEL_VOUCHER', 'BUS_TICKET', 'DIRECT_CASH'],
    paymentMethod: 'SURVIVOR_DIRECT',
    typicalAmount: '$50 to $300 in immediate discretionary micro-aid',
    knownFundingLimits: 'Discretionary pooled fund managed by rotating town clergy; limited to local community emergency escape/transportation needs',
    eligibility: 'Anyone physically present in participating rural Central Texas towns (Elgin, Bastrop, Lockhart, Luling, San Marcos outskirts) experiencing an acute escape bottleneck.',
    documentationRequired: [
      'Informal conversation with presiding pastor or town social worker',
      'Zero formal ID or police report required in emergency situations'
    ],
    referralRequirement: 'Local sheriff dispatcher, municipal library desk, or food pantry liaison',
    shelterConnectionRequired: false,
    policeReportRequired: false,
    incomeRestriction: 'Demonstrated immediate crisis shortfall',
    employmentDependency: 'None',
    applicationWindow: 'Same-day emergency assistance',
    whatCanBlockAccess: [
      'Informal structure requires knowing which local pastor holds the checkbook for the current month',
      'Funding amounts are small ($50–$300) and intended as immediate bridge aid'
    ],
    accessFrictions: ['NO_POLICE_REPORT_REQUIRED', 'NO_SHELTER_STAY_REQUIRED', 'SAME_DAY_POSSIBLE'],
    whatToDoNext: 'Ask the local county sheriff dispatcher, town library clerk, or local food pantry director for the contact number of the current presiding Ministerial Alliance secretary.',
    howToApply: 'Contact local town ministerial liaison or community pantry coordinator.',
    sourceUrl: 'https://mapswithteeth.org/texas',
    primaryAuthoritativeSource: 'Central Texas Ecumenical Pastoral Alliances Field Audit',
    lastReviewedDate: '2026-08-25',
    dateLastVerified: '2026-08-25',
    verificationStatus: 'PUBLIC_SOURCE_CHECKED',
    isStatutoryRight: false,
    whyMissed: 'Completely unindexed in 211 and digital search engines; operates as pooled discretionary checking accounts managed by rotating local town pastors.',
    workaround: 'In rural towns where no shelters exist (Elgin, Bastrop, Lockhart, Luling, San Marcos outskirts), the Ministerial Alliance pool can issue same-day $50–$300 emergency gas cards, 1–2 nights at a local roadside motel, or Greyhound vouchers. ID and documentation rules are completely flexible.',
    accessNotes: 'Ask local county sheriff dispatchers, municipal library desks, or the local community food pantry director for the phone number of the current rotating Ministerial Alliance treasurer.'
  }
];

// Append new resources to OTHER_WAYS_THROUGH_RESOURCES
const lastBracketIndex = owt.lastIndexOf('];');
if (lastBracketIndex !== -1) {
  const jsonStrings = newResources.map(r => '  ' + JSON.stringify(r, null, 2).replace(/\n/g, '\n  ')).join(',\n');
  const updatedOwt = owt.slice(0, lastBracketIndex).trimEnd() + ',\n' + jsonStrings + '\n];\n';
  fs.writeFileSync('src/data/otherWaysThrough.ts', updatedOwt, 'utf8');
  console.log('Successfully appended 19 resources to src/data/otherWaysThrough.ts');
} else {
  console.error('Could not find closing bracket in otherWaysThrough.ts');
}
